export const scienceQ1 = "Oil, natural gas and coal are examples of ..."
export const scienceQ1CorrectAnswer = "Fossil fuels"
export const scienceQ1A1 = "Renewable resources"
export const scienceQ1A2 = "Biofuels"
export const scienceQ1A3 = "Geothermal resources"

export const scienceQ2 = "Which of the following is an example of genetic engineering?"
export const scienceQ2CorrectAnswer = "Inserting a gene into plants that makes them resistant to insects"
export const scienceQ2A1 = "Finding the sequences of bases in plant DNA"
export const scienceQ2A2 = "Growing a whole plant from a single cell"
export const scienceQ2A3 = "Attaching the root of one type of plant to the stem of another type of plant"

export const scienceQ3 = "What is the main cause of seasons on the Earth?"
export const scienceQ3CorrectAnswer = "The tilt of the Earth's axis in relation to the sun"
export const scienceQ3A1 = "Changes in the amount of energy coming from the sun"
export const scienceQ3A2 = "The speed that the Earth rotates around the sun"
export const scienceQ3A3 = "The distance between the Earth and the sun"

export const mathQ1 = "What is three fifth of 100?"
export const mathQ1CorrectAnswer = "60"
export const mathQ1A1 = "3"
export const mathQ1A2 = "5"
export const mathQ1A3 = "20"

export const mathQ2 = "What is 7% equal to?"
export const mathQ2CorrectAnswer = "0.07"
export const mathQ2A1 = "0.007"
export const mathQ2A2 = "0.7"
export const mathQ2A3 = "7"

export const mathQ3 = "What is the value of x if x^2 = 576"
export const mathQ3CorrectAnswer = "24"
export const mathQ3A1 = "16"
export const mathQ3A2 = "14"
export const mathQ3A3 = "23"